### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by Eeems**
I've made the following enhancements to the bot that you may be interested in merging:

- Switched to using tail instead of fsnotify/grab last line to attempt to fix bug where log lines are missed if they happen too quickly
- Added a couple simple commands to the discord side of the bot:
  - !online - See how many online players there are
  - !seed - See what the seed is
  - !evolution - See what the current evolution status is
- The bot will check the player count every minute, or when it sees that a player has joined or parted, just to make sure it stays in sync
- Discord status will now reflect some of the current things happening in the game. For example:
  - Players are online and no other events are happening:
    image
  - No players are online:
    image

I'd be happy to close this and open a new PR with only portions of this if you'd prefer.

### CODE REVIEW

**Comment by Mattie112** [comment]
Thank you for the improvements, looks great! I will try them out later this week just as a quick test but I see no problem adding these features! The log reading part was always a bit "meh" (to bad you can't access the network with a Factorio mod) so any improvements (or other options) are a big plus. It is still on my todo list to change that a bit where it has some internal pointer and knows exactly where it was when reading but yeah I need some time haha :)

**Comment by Mattie112** [comment]
Sorry for the late reply, have been sick.

I just looked at the code and a couple of things / questions:

- The tests fail (all goroutines are asleep)
- I do like the added goroutines
- Might be nicer (for tests) to not have global chan variable but provide them as input to the functions (also in my code)
- Why do you want to keep the player count in sync? Did you observe any issues with that? Why do we need to keep that in memory? When the player count is requested we can also do a `/players` command right then.
- Did you also observe missing / duplicate logging when using the `tail.TailFile` lib?

At least I'd like the tests to work before merging, all other things can also be done in a different commit. I want to look into the github actions as well in order to run the tests (and builds) automatically. I might have some time tonight to look into the tests myself.

Just a quick look at the tests:
- `fatal error: all goroutines are asleep - deadlock!` -> not sure yet
- `goroutine 20 [chan send (nil chan)]:` -> the `commands` chan is not initialized when used by the tests, possible we can mock this? Need to look a bit more into golang testing.

**Comment by Mattie112** [comment]
(and added a workflow to auto-run the tests, merged with main)

**Comment by Mattie112** [comment]
Just tested the changes (https://hub.docker.com/layers/mattie112/factorigo-chat-bot/pr6/images/sha256-858eb7a6f2a63fac9cc09b906221af62a2a49a64b2811b8959ccac0e990e620f?context=repo)

After starting the bot immediately starts spamming all old logs/chats. At my server the log file is not cleared after a restart or something. How does this work for you? Either the bot must clear the file (but we should ask the user if they want this), or possible only read the last 1~5 lines upon (re)start. Any ideas?

**Comment by Mattie112** [comment]
This also does not seem expected to me:
image

**Comment by Mattie112** [comment]
"-1 players":

image

**Comment by Eeems** [comment]
> This also does not seem expected to me: image

> "-1 players":
> 
> image
> 
> A minute later "0 players" is reported correctly

This sounds like it's all related to it reading through the log line instead of starting at the end. Whenever it finds a part/join log line it queries for the current player count again. -1 players is just when it fails to load properly.

> Sorry for the late reply, have been sick.

No worries! Hope you feel better!

> 
> I just looked at the code and a couple of things / questions:
> 
>  * The tests fail (all goroutines are asleep)

Apologies, this is my first time doing major changes to a go project, so I'm still learning the language and standards.

> 
> * I do like the added goroutines

Thanks!

> 
>  * Might be nicer (for tests) to not have global chan variable but provide them as input to the functions (also in my code)

I was just following what I was seeing for standards in the code already, but I do agree, it would make more sense to avoid globals.

> 
>  * Why do you want to keep the player count in sync? Did you observe any issues with that? Why do we need to keep that in memory? When the player count is requested we can also do a `/players` command right then.

Since I was seeing issues with log lines being skipped due to how the log file parsing was done previously, I thought it would be safer to just query for the current count.

> 
> * Did you also observe missing / duplicate logging when using the `tail.TailFile` lib?

I didn't, but I didn't do a ton of testing as I didn't have a play session scheduled with anybody at that time.

> 
> 
> At least I'd like the tests to work before merging, all other things can also be done in a different commit. I want to look into the github actions as well in order to run the tests (and builds) automatically. I might have some time tonight to look into the tests myself.

I agree, I'll try to spend some time this weekend getting them working.

**Comment by Eeems** [comment]
It looks like we might be able to use Config.Location to start tailing from the end of the file instead of the start: https://pkg.go.dev/github.com/nxadm/tail#Config

**Comment by Mattie112** [comment]
No worries about the tests etc we are all here to learn (and I am also not (yet) good with tests). I will see if I can ask someone with a bit more testing experience how he would fix this. For nu just getting the messages from the channel solves the testing problem. They are now also ran here in github so you can see if they are good or not :)

I did not see the "location" option, that might indeed be a good one to check!

So the current state is:
- tests are fixed
- online player amount is changed (and hopefully fixed)
- tail config is changed (need to test)
- todo is to look and see why the bot status is changed every few seconds

Not sure if I'll have a lot of time today but if I do I'll post a message here so we don't do duplicate work :)

**Comment by Eeems** [comment]
I'm fairly sure that the status change every two seconds was due to not starting at the end of the log. I wasn't able to replicate it myself.

**Comment by Mattie112** [comment]
I still have the same problem with old lines being parsed on startup, let me see if I can create a test to "prove" it.

**Comment by Eeems** [comment]
Very odd, when I was making the change I had a test case that would have resulted in extra join/part lines, but they didn't happen.

**Comment by Mattie112** [comment]
Well I think I did not pushed it to docker correctly or something (that is how I test to get it on my server). I wrote a test (took quite some time haha) and it was not failing so hm after a lot of time I thought well it seems to work let's just test it again.

So yeahhhhhhh. Unfortunately I am now out of time to test some stuff ingame but it is not spamming so that is a plus! I hope to test it tomorrow.

Feel free to change things to the test I made :)

**Comment by Mattie112** [comment]
I think this is the last "issue":
image

I'll change it to "watching". I will also see if I can change it back to the regular state x time after a launch.

**Comment by Eeems** [comment]
> I think this is the last "issue": image
> 
> I'll change it to "watching". I will also see if I can change it back to the regular state x time after a launch.

I guess you are at the point of launching rockets semi-regularily. It _should_ clear when the next player count sync happens here:
https://github.com/Mattie112/FactoriGOChatBot/pull/6/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R73-R75

That might not be quick enough though?

**Comment by Mattie112** [comment]
Ah it might be that indeed, there could very well be some rocket (playing space exploration) be on auto launch. Well in that case I'll just change it to "watches" and then I think it is fine to merge :D

**Comment by Eeems** [comment]
Player death messages should probably be changed as well: https://github.com/Mattie112/FactoriGOChatBot/pull/6/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R156

**Comment by Eeems** [comment]
🚀

**Comment by Mattie112** [comment]
I will also create a release in a moment! (still need to automate that!)

**Comment by Mattie112** [comment]
Allright it should be live now! https://github.com/Mattie112/FactoriGOChatBot/releases/tag/v0.6.0

Again thanks for the work!

**Pull request merged**
